/**
 * Kaggle Chess Cheating Dataset — Integration Validation Test
 *
 * Validates our anti-cheat pipeline against 48,000 real bot games where one side
 * uses Stockfish (cheating) and the other uses Maia (human-like).
 *
 * Ground truth comes from the dataset labels:
 *   Liste_cheat_white / Liste_cheat_black: 1 = cheating, 0 = honest
 *
 * This test requires two pre-built fixtures (generated by scripts/prepare_kaggle_fixtures.py):
 *   tests/fixtures/kaggle_sample.json     — per-game move history (100 games)
 *   tests/fixtures/kaggle_analyzed.json   — pre-run GameAnalyzer metrics (same 100 games)
 *
 * Run fixtures generation once:
 *   pip install kagglehub pandas python-chess stockfish
 *   python scripts/prepare_kaggle_fixtures.py
 *
 * This test is SKIPPED automatically if fixture files are absent so CI pipelines
 * that don't have Kaggle credentials are unaffected.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { existsSync, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_RAW     = join(__dirname, '../fixtures/kaggle_sample.json');
const FIXTURE_ANALYZED = join(__dirname, '../fixtures/kaggle_analyzed.json');

const fixturesExist = existsSync(FIXTURE_RAW) && existsSync(FIXTURE_ANALYZED);

// ---------------------------------------------------------------------------
// Classification thresholds mirroring FairPlayService penalties
// ---------------------------------------------------------------------------

/** Returns a [0,100] trust score from pre-computed GameAnalyzer metrics. */
function computeTrustScore(metrics, userRating = 1500) {
  const expectedStrength = expectedStrengthForRating(userRating);
  const deviation = metrics.strengthScore - expectedStrength;
  const zScore = deviation / 12; // single-game estimate

  let trust = 100;

  // z-score penalties
  if (zScore > 4.5) trust -= 35;
  else if (zScore > 3.0) trust -= 30;
  else if (zScore > 2.5) trust -= 20;
  else if (zScore > 2.0) trust -= 10;

  // Timing suspicion
  if (metrics.timingSuspicion > 0.7) trust -= 10;
  else if (metrics.timingSuspicion > 0.5) trust -= 5;

  // Flat timing — must mirror FairPlayService penalties exactly
  if (metrics.flatTimingCV !== null) {
    if (metrics.flatTimingCV < 0.10) trust -= 45;
    else if (metrics.flatTimingCV < 0.15) trust -= 45;
    else if (metrics.flatTimingCV < 0.25) trust -= 15;
    else if (metrics.flatTimingCV < 0.40) trust -= 8;
  }

  // Engine correlation
  if (metrics.engineCorr > 0.85) trust -= 10;
  else if (metrics.engineCorr > 0.75) trust -= 5;

  return Math.max(0, Math.min(100, trust));
}

function expectedStrengthForRating(rating) {
  const anchors = [[800,35],[1200,50],[1600,60],[2000,72],[2400,82],[2700,88]];
  const clamped = Math.max(800, Math.min(2700, rating));
  for (let i = 0; i < anchors.length - 1; i++) {
    const [r1,s1] = anchors[i]; const [r2,s2] = anchors[i+1];
    if (clamped >= r1 && clamped <= r2) {
      return s1 + ((clamped-r1)/(r2-r1)) * (s2-s1) + 3;
    }
  }
  return 88;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function classifyPlayer(metrics, rating) {
  return computeTrustScore(metrics, rating) < 60;
}

function computeMetrics(predictions, truths) {
  let tp = 0, fp = 0, tn = 0, fn = 0;
  for (let i = 0; i < predictions.length; i++) {
    const pred = predictions[i], truth = truths[i];
    if (truth && pred) tp++;
    else if (!truth && pred) fp++;
    else if (!truth && !pred) tn++;
    else fn++;
  }
  const precision  = tp + fp > 0 ? tp / (tp + fp) : 0;
  const recall     = tp + fn > 0 ? tp / (tp + fn) : 0;
  const f1         = precision + recall > 0 ? 2 * precision * recall / (precision + recall) : 0;
  const fpr        = tn + fp > 0 ? fp / (tn + fp) : 0;
  return { tp, fp, tn, fn, precision, recall, f1, fpr };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe.skipIf(!fixturesExist)(
  'Kaggle Dataset Validation (requires scripts/prepare_kaggle_fixtures.py)',
  () => {
    let sample, analyzed;

    beforeAll(() => {
      sample   = JSON.parse(readFileSync(FIXTURE_RAW, 'utf-8'));
      analyzed = JSON.parse(readFileSync(FIXTURE_ANALYZED, 'utf-8'));
      console.log(`\nLoaded ${sample.games.length} games from Kaggle fixture`);
      console.log(`  Cheating white: ${sample.games.filter(g => g.cheatingWhite).length}`);
      console.log(`  Cheating black: ${sample.games.filter(g => g.cheatingBlack).length}`);
      console.log(`  Clean games: ${sample.games.filter(g => !g.cheatingWhite && !g.cheatingBlack).length}`);
    });

    // -----------------------------------------------------------------------
    // Metric range checks (sanity checks on pre-computed data)
    // -----------------------------------------------------------------------

    it('cheating players have higher engineCorr than honest players on average', () => {
      const cheatCorrs  = [];
      const honestCorrs = [];

      for (const game of analyzed.games) {
        if (game.white) {
          (game.cheatingWhite ? cheatCorrs : honestCorrs).push(game.white.engineCorr);
        }
        if (game.black) {
          (game.cheatingBlack ? cheatCorrs : honestCorrs).push(game.black.engineCorr);
        }
      }

      const avg = arr => arr.reduce((a, b) => a + b, 0) / arr.length;
      const cheatAvg  = avg(cheatCorrs);
      const honestAvg = avg(honestCorrs);

      console.log(`\nEngine correlation — cheat: ${cheatAvg.toFixed(3)}, honest: ${honestAvg.toFixed(3)}`);
      // Gap may be modest with partial-cheating games; verify direction holds
      expect(cheatAvg).toBeGreaterThan(honestAvg + 0.05);
    });

    it('cheating players have lower ACPL than honest players on average', () => {
      const cheatACPLs  = [];
      const honestACPLs = [];

      for (const game of analyzed.games) {
        if (game.white) (game.cheatingWhite ? cheatACPLs : honestACPLs).push(game.white.acpl);
        if (game.black) (game.cheatingBlack ? cheatACPLs : honestACPLs).push(game.black.acpl);
      }

      const avg = arr => arr.reduce((a, b) => a + b, 0) / arr.length;
      const cheatAvg  = avg(cheatACPLs);
      const honestAvg = avg(honestACPLs);

      console.log(`ACPL — cheat: ${cheatAvg.toFixed(1)}, honest: ${honestAvg.toFixed(1)}`);
      expect(cheatAvg).toBeLessThan(honestAvg - 15);
    });

    it('cheating players have lower flatTimingCV (more uniform think times)', () => {
      const cheatCVs  = [];
      const honestCVs = [];

      for (const game of analyzed.games) {
        if (game.white?.flatTimingCV != null) {
          (game.cheatingWhite ? cheatCVs : honestCVs).push(game.white.flatTimingCV);
        }
        if (game.black?.flatTimingCV != null) {
          (game.cheatingBlack ? cheatCVs : honestCVs).push(game.black.flatTimingCV);
        }
      }

      if (cheatCVs.length === 0 || honestCVs.length === 0) {
        console.warn('Not enough flatTimingCV data — may need more games');
        return;
      }

      const avg = arr => arr.reduce((a, b) => a + b, 0) / arr.length;
      const cheatAvg  = avg(cheatCVs);
      const honestAvg = avg(honestCVs);

      console.log(`FlatTimingCV — cheat: ${cheatAvg.toFixed(3)}, honest: ${honestAvg.toFixed(3)}`);
      expect(cheatAvg).toBeLessThan(honestAvg);
    });

    it('cheating players tend to show negative or near-zero cpLossComplexityCorr', () => {
      const cheatCorrs  = [];
      const honestCorrs = [];

      for (const game of analyzed.games) {
        if (game.white?.cpLossComplexityCorr != null) {
          (game.cheatingWhite ? cheatCorrs : honestCorrs).push(game.white.cpLossComplexityCorr);
        }
        if (game.black?.cpLossComplexityCorr != null) {
          (game.cheatingBlack ? cheatCorrs : honestCorrs).push(game.black.cpLossComplexityCorr);
        }
      }

      if (cheatCorrs.length === 0 || honestCorrs.length === 0) return;

      const avg = arr => arr.reduce((a, b) => a + b, 0) / arr.length;
      const cheatAvg  = avg(cheatCorrs);
      const honestAvg = avg(honestCorrs);

      console.log(`cpLoss-Complexity corr — cheat: ${cheatAvg.toFixed(3)}, honest: ${honestAvg.toFixed(3)}`);
      // Both should be near zero; cheaters should not have strong positive correlation.
      // With partial-cheating games this signal is noisy — just verify cheat corr is near-zero.
      expect(Math.abs(cheatAvg)).toBeLessThan(0.30);
    });

    // -----------------------------------------------------------------------
    // Classification accuracy
    // -----------------------------------------------------------------------

    it('achieves >= 90% recall (TPR) on cheating players', () => {
      const predictions = [], truths = [];

      for (const game of analyzed.games) {
        const wRating = game.eloWhite > 0 ? game.eloWhite : 1500;
        const bRating = game.eloBlack > 0 ? game.eloBlack : 1500;
        if (game.white) {
          predictions.push(classifyPlayer(game.white, wRating));
          truths.push(Boolean(game.cheatingWhite));
        }
        if (game.black) {
          predictions.push(classifyPlayer(game.black, bRating));
          truths.push(Boolean(game.cheatingBlack));
        }
      }

      const { tp, fp, tn, fn, precision, recall, f1, fpr } = computeMetrics(predictions, truths);
      console.log(`\nClassification results:`);
      console.log(`  TP=${tp} FP=${fp} TN=${tn} FN=${fn}`);
      console.log(`  Precision=${(precision*100).toFixed(1)}%`);
      console.log(`  Recall/TPR=${(recall*100).toFixed(1)}%`);
      console.log(`  F1=${(f1*100).toFixed(1)}%`);
      console.log(`  FPR=${(fpr*100).toFixed(1)}%`);

      expect(recall).toBeGreaterThanOrEqual(0.90);
    });

    it('achieves <= 25% false positive rate on honest players', () => {
      const predictions = [], truths = [];

      for (const game of analyzed.games) {
        const wRating = game.eloWhite > 0 ? game.eloWhite : 1500;
        const bRating = game.eloBlack > 0 ? game.eloBlack : 1500;
        if (game.white) {
          predictions.push(classifyPlayer(game.white, wRating));
          truths.push(Boolean(game.cheatingWhite));
        }
        if (game.black) {
          predictions.push(classifyPlayer(game.black, bRating));
          truths.push(Boolean(game.cheatingBlack));
        }
      }

      const { fpr } = computeMetrics(predictions, truths);
      expect(fpr).toBeLessThanOrEqual(0.25);
    });

    it('produces a full detection report per game', () => {
      const report = analyzed.games.map(game => {
        const wRating = game.eloWhite > 0 ? game.eloWhite : 1500;
        const bRating = game.eloBlack > 0 ? game.eloBlack : 1500;
        return {
          gameId: game.gameId,
          white: game.white ? {
            flagged: classifyPlayer(game.white, wRating),
            truth: Boolean(game.cheatingWhite),
            engineCorr: game.white.engineCorr,
            acpl: game.white.acpl,
            flatTimingCV: game.white.flatTimingCV,
            strengthScore: game.white.strengthScore,
          } : null,
          black: game.black ? {
            flagged: classifyPlayer(game.black, bRating),
            truth: Boolean(game.cheatingBlack),
            engineCorr: game.black.engineCorr,
            acpl: game.black.acpl,
            flatTimingCV: game.black.flatTimingCV,
            strengthScore: game.black.strengthScore,
          } : null,
        };
      });

      // Sanity: every game has a result
      expect(report).toHaveLength(analyzed.games.length);
      for (const row of report) {
        expect(row.gameId).toBeDefined();
      }
    });
  }
);
